/**
 * Route path registry (repo convention: PUBLIC_NAVIGATION / PRIVATE_NAVIGATION
 * objects, never inline path strings).
 */

// ** Unauthenticated paths **
export const PUBLIC_NAVIGATION = Object.freeze({
  home: '/',
  login: '/login',
  register: '/register',
});

// ** Authenticated paths **
export const PRIVATE_NAVIGATION = Object.freeze({
  // ── Legacy flat paths (kept for backward compatibility / redirects) ──
  dashboard: '/dashboard',
  availableExams: '/exams',
  examInterface: '/exam/:examId/attempt/:attemptId',
  examResult: '/exam/result/:attemptId',
  myHistory: '/history',
  mockHistory: '/mock-history',
  questionBank: '/question-bank',
  createQuestion: '/question-bank/create',
  importQuestions: '/question-bank/import',
  editQuestion: '/question-bank/:id/edit',
  languages: '/languages',
  importTranslations: '/languages/import',
  examBlueprints: '/exam-blueprints',
  examScheduling: '/exam-scheduling',
  strategyRules: '/strategy-rules',
  leaderboard: '/leaderboard',
  historicalDatasets: '/historical-datasets',
  performanceTrends: '/performance-trends',
  parentDashboard: '/parent-dashboard',
  institutionDashboard: '/institution/dashboard',
  institutionStudents: '/institution/students',
  institutionRankList: '/institution/rank-list',
  institutionBatches: '/institution/batches',
  institutionBulkUpload: '/institution/bulk-upload',
  institutionReports: '/institution/reports',
  institutionProfile: '/institution/profile',
  adminControlCenter: '/admin',
  adminApprovalQueue: '/admin/approvals',
  adminAuditLogs: '/admin/audit-logs',
  adminNotifications: '/admin/notifications',
  notifications: '/notifications',
  examDetails: '/exams/:examId',
  academicCalendar: '/exam-calendar',
  profile: '/profile',

  // ── Student role-prefixed routes ──
  studentDashboard: '/student/dashboard',
  studentExams: '/student/exams',
  studentMockTests: '/student/mock-tests',
  studentMockHistory: '/student/mock-history',
  studentExamDetails: '/student/exams/:examId',
  studentNotifications: '/student/notifications',
  studentHistory: '/student/history',
  studentCalendar: '/student/exam-calendar',
  studentTrends: '/student/performance-trends',
  studentComparison: '/student/comparison',
  studentMockComparison: '/student/mock-comparison',
  studentLeaderboard: '/student/leaderboard',
  studentProfile: '/student/profile',

  // ── Admin role-prefixed routes ──
  adminDashboard: '/admin/dashboard',
  adminQuestionBank: '/admin/question-bank',
  adminCreateQuestion: '/admin/question-bank/create',
  adminImportQuestions: '/admin/question-bank/import',
  adminEditQuestion: '/admin/question-bank/:id/edit',
  adminLanguages: '/admin/languages',
  adminTranslations: '/admin/translations',
  adminImportTranslations: '/admin/languages/import',
  adminExamBlueprints: '/admin/exam-blueprints',
  adminAutoGenerateExam: '/admin/exams/generate',
  adminMockTests: '/admin/mock-tests',
  adminExams: '/admin/mock-tests',
  adminExamManager: '/admin/exam-manager',
  adminUploadPaper: '/admin/exam-manager/upload',
  adminAnswerKey: '/admin/exam-manager/answer-key',
  adminExamImportHistory: '/admin/exam-manager/history',
  adminExamScheduling: '/admin/exam-scheduling',
  adminStrategyRules: '/admin/strategy-rules',
  adminLeaderboard: '/admin/leaderboard',
  adminHistoricalDatasets: '/admin/historical-datasets',
  adminControlCenterPage: '/admin/control-center',
  adminApprovalQueuePage: '/admin/approval-queue',
  adminAuditLogsPage: '/admin/audit-logs-page',
  adminNotificationsPage: '/admin/notifications-page',
  adminChapters: '/admin/chapters',
  adminExamResults: '/admin/exams/results',
  adminCompletedExams: '/admin/completed-exams',
  adminBulkStudents: '/admin/students/bulk-register',
  adminStudents: '/admin/students',
  adminSchools: '/admin/schools',
  adminProfile: '/admin/profile',

  // ── Super Admin role-prefixed routes ──
  superAdminDashboard: '/super-admin/dashboard',
  superAdminRegistrations: '/super-admin/registrations',
  superAdminBulkStudents: '/super-admin/students/bulk-register',
  superAdminStudents: '/super-admin/students',
  superAdminSchools: '/super-admin/schools',
  superAdminQuestionBank: '/super-admin/question-bank',
  superAdminChapters: '/super-admin/chapters',
  superAdminCreateQuestion: '/super-admin/question-bank/create',
  superAdminImportQuestions: '/super-admin/question-bank/import',
  superAdminEditQuestion: '/super-admin/question-bank/:id/edit',
  superAdminLanguages: '/super-admin/languages',
  superAdminTranslations: '/super-admin/translations',
  superAdminImportTranslations: '/super-admin/languages/import',
  superAdminExamBlueprints: '/super-admin/exam-blueprints',
  superAdminAutoGenerateExam: '/super-admin/exams/generate',
  superAdminMockTests: '/super-admin/mock-tests',
  superAdminExams: '/super-admin/mock-tests',
  superAdminExamResults: '/super-admin/exams/results',
  superAdminExamResultProcessing: '/super-admin/exams/result-processing',
  superAdminCompletedExams: '/super-admin/completed-exams',
  superAdminExamManager: '/super-admin/exam-manager',
  superAdminUploadPaper: '/super-admin/exam-manager/upload',
  superAdminAnswerKey: '/super-admin/exam-manager/answer-key',
  superAdminExamImportHistory: '/super-admin/exam-manager/history',
  superAdminExamScheduling: '/super-admin/exam-scheduling',
  superAdminStrategyRules: '/super-admin/strategy-rules',
  superAdminLeaderboard: '/super-admin/leaderboard',
  superAdminHistoricalDatasets: '/super-admin/historical-datasets',
  superAdminControlCenter: '/super-admin/control-center',
  superAdminApprovalQueue: '/super-admin/approval-queue',
  superAdminAuditLogs: '/super-admin/audit-logs',
  superAdminNotifications: '/super-admin/notifications',
  superAdminInstitutionDashboard: '/super-admin/institution',
  superAdminInstitutionBatches: '/super-admin/institution/batches',
  superAdminInstitutionBulkUpload: '/super-admin/institution/bulk-upload',
  superAdminInstitutionReports: '/super-admin/institution/reports',
  superAdminStaff: '/super-admin/staff',
  superAdminBilling: '/super-admin/billing',
  superAdminAcademicCalendar: '/super-admin/academic-calendar',
  superAdminProfile: '/super-admin/profile',

  // ── Staff role-prefixed routes ──
  staffDashboard: '/staff/dashboard',
  staffBilling: '/staff/billing',
  staffSchools: '/staff/schools',
  staffBulkStudents: '/staff/students/bulk-register',
  staffStudents: '/staff/students',
  staffQuestionBank: '/staff/question-bank',
  staffTranslations: '/staff/translations',
  staffExams: '/staff/exams',
  staffScheduledExams: '/staff/exams/pending-paper',
  staffReports: '/staff/reports',
  staffAnswerKey: '/staff/answer-key',
  staffApprovalQueue: '/staff/approvals',
  staffNotifications: '/staff/notifications',
  staffProfile: '/staff/profile',

  // ── General Manager role-prefixed routes ──
  generalManagerDashboard: '/general-manager/dashboard',
  generalManagerStudents: '/general-manager/students',
  generalManagerBulkStudents: '/general-manager/students/bulk-register',
  generalManagerSchools: '/general-manager/schools',
  generalManagerQuestionBank: '/general-manager/question-bank',
  generalManagerChapters: '/general-manager/chapters',
  generalManagerCreateQuestion: '/general-manager/question-bank/create',
  generalManagerImportQuestions: '/general-manager/question-bank/import',
  generalManagerLanguages: '/general-manager/languages',
  generalManagerTranslations: '/general-manager/translations',
  generalManagerImportTranslations: '/general-manager/languages/import',
  generalManagerExamBlueprints: '/general-manager/exam-blueprints',
  generalManagerExams: '/general-manager/exams',
  generalManagerExamScheduling: '/general-manager/exam-scheduling',
  generalManagerUploadPaper: '/general-manager/exam-manager/upload',
  generalManagerAnswerKey: '/general-manager/exam-manager/answer-key',
  generalManagerCompletedExams: '/general-manager/completed-exams',
  generalManagerReports: '/general-manager/reports',
  generalManagerApprovalQueue: '/general-manager/approvals',
  generalManagerBilling: '/general-manager/billing',
  generalManagerStrategyRules: '/general-manager/strategy-rules',
  generalManagerLeaderboard: '/general-manager/leaderboard',
  generalManagerHistoricalDatasets: '/general-manager/historical-datasets',
  generalManagerAuditLogs: '/general-manager/audit-logs',
  generalManagerNotifications: '/general-manager/notifications',
  generalManagerProfile: '/general-manager/profile',

  // ── Manager role-prefixed routes ──
  managerDashboard: '/manager/dashboard',
  managerStudents: '/manager/students',
  managerSchools: '/manager/schools',
  managerQuestionBank: '/manager/question-bank',
  managerTranslations: '/manager/translations',
  managerExams: '/manager/exams',
  managerReports: '/manager/reports',
  managerApprovalQueue: '/manager/approvals',
  managerBilling: '/manager/billing',
  managerNotifications: '/manager/notifications',
  managerProfile: '/manager/profile',

  // ── Operator role-prefixed routes ──
  operatorDashboard: '/operator/dashboard',
  operatorStudents: '/operator/students',
  operatorBulkStudents: '/operator/students/bulk-register',
  operatorSchools: '/operator/schools',
  operatorQuestionBank: '/operator/question-bank',
  operatorChapters: '/operator/chapters',
  operatorCreateQuestion: '/operator/question-bank/create',
  operatorImportQuestions: '/operator/question-bank/import',
  operatorLanguages: '/operator/languages',
  operatorTranslations: '/operator/translations',
  operatorImportTranslations: '/operator/languages/import',
  operatorExamBlueprints: '/operator/exam-blueprints',
  operatorExams: '/operator/exams',
  operatorExamScheduling: '/operator/exam-scheduling',
  operatorScheduledExams: '/operator/exams/pending-paper',
  operatorUploadPaper: '/operator/exam-manager/upload',
  operatorExamUploadPaper: '/operator/exams/:examId/question-paper/upload',
  operatorViewQuestionPaper: '/operator/exams/:examId/question-paper/view',
  operatorAnswerKey: '/operator/exam-manager/answer-key',
  operatorAnswerKeySchedule: '/operator/exam-manager/answer-key/:scheduleId',
  operatorViewAnswerKey: '/operator/exam-manager/answer-key/:scheduleId/view',
  operatorExamImportHistory: '/operator/exam-manager/history',
  operatorCompletedExams: '/operator/completed-exams',
  operatorReports: '/operator/reports',
  operatorApprovalQueue: '/operator/approvals',
  operatorBilling: '/operator/billing',
  operatorLeaderboard: '/operator/leaderboard',
  operatorNotifications: '/operator/notifications',
  operatorProfile: '/operator/profile',

  // ── Accountant role-prefixed routes ──
  accountantDashboard: '/accountant/dashboard',
  accountantBilling: '/accountant/billing',
  accountantReports: '/accountant/reports',
  accountantNotifications: '/accountant/notifications',
  accountantProfile: '/accountant/profile',

  // ── Sales Agent role-prefixed routes ──
  salesAgentDashboard: '/sales-agent/dashboard',
  salesAgentSchools: '/sales-agent/schools',
  salesAgentReports: '/sales-agent/reports',
  salesAgentNotifications: '/sales-agent/notifications',
  salesAgentProfile: '/sales-agent/profile',

  // ── Parent role-prefixed routes ──
  parentDashboardHome: '/parent/dashboard',
  parentWardProgress: '/parent/ward-progress',
  parentProfile: '/parent/profile',
});

// ** Misc **
export const NOT_FOUND_PATH = '*';
