/**
 * Route path registry (repo convention: PUBLIC_NAVIGATION / PRIVATE_NAVIGATION
 * objects, never inline path strings).
 */

// ** Unauthenticated paths **
export const PUBLIC_NAVIGATION = Object.freeze({
  home: '/',
  login: '/login',
});

// ** Authenticated paths **
export const PRIVATE_NAVIGATION = Object.freeze({
  // ── Legacy flat paths (kept for backward compatibility / redirects) ──
  dashboard: '/dashboard',
  availableExams: '/exams',
  examInterface: '/exam/:examId/attempt/:attemptId',
  examResult: '/exam/result/:attemptId',
  myHistory: '/history',
  mockHistory: '/mock-history',
  questionBank: '/question-bank',
  createQuestion: '/question-bank/create',
  importQuestions: '/question-bank/import',
  editQuestion: '/question-bank/:id/edit',
  languages: '/languages',
  importTranslations: '/languages/import',
  examBlueprints: '/exam-blueprints',
  examScheduling: '/exam-scheduling',
  strategyRules: '/strategy-rules',
  leaderboard: '/leaderboard',
  historicalDatasets: '/historical-datasets',
  performanceTrends: '/performance-trends',
  parentDashboard: '/parent-dashboard',
  institutionDashboard: '/institution/dashboard',
  institutionBatches: '/institution/batches',
  institutionBulkUpload: '/institution/bulk-upload',
  institutionReports: '/institution/reports',
  institutionProfile: '/institution/profile',
  adminControlCenter: '/admin',
  adminApprovalQueue: '/admin/approvals',
  adminAuditLogs: '/admin/audit-logs',
  adminNotifications: '/admin/notifications',
  notifications: '/notifications',
  examDetails: '/exams/:examId',
  academicCalendar: '/exam-calendar',
  profile: '/profile',

  // ── Student role-prefixed routes ──
  studentDashboard: '/student/dashboard',
  studentExams: '/student/exams',
  studentMockTests: '/student/mock-tests',
  studentMockHistory: '/student/mock-history',
  studentExamDetails: '/student/exams/:examId',
  studentNotifications: '/student/notifications',
  studentHistory: '/student/history',
  studentCalendar: '/student/exam-calendar',
  studentTrends: '/student/performance-trends',
  studentComparison: '/student/comparison',
  studentMockComparison: '/student/mock-comparison',
  studentLeaderboard: '/student/leaderboard',
  studentProfile: '/student/profile',

  // ── Admin role-prefixed routes ──
  adminDashboard: '/admin/dashboard',
  adminQuestionBank: '/admin/question-bank',
  adminCreateQuestion: '/admin/question-bank/create',
  adminImportQuestions: '/admin/question-bank/import',
  adminEditQuestion: '/admin/question-bank/:id/edit',
  adminLanguages: '/admin/languages',
  adminTranslations: '/admin/translations',
  adminImportTranslations: '/admin/languages/import',
  adminExamBlueprints: '/admin/exam-blueprints',
  adminAutoGenerateExam: '/admin/exams/generate',
  adminMockTests: '/admin/mock-tests',
  adminExams: '/admin/mock-tests',
  adminExamManager: '/admin/exam-manager',
  adminUploadPaper: '/admin/exam-manager/upload',
  adminExamImportHistory: '/admin/exam-manager/history',
  adminExamScheduling: '/admin/exam-scheduling',
  adminStrategyRules: '/admin/strategy-rules',
  adminLeaderboard: '/admin/leaderboard',
  adminHistoricalDatasets: '/admin/historical-datasets',
  adminControlCenterPage: '/admin/control-center',
  adminApprovalQueuePage: '/admin/approval-queue',
  adminAuditLogsPage: '/admin/audit-logs-page',
  adminNotificationsPage: '/admin/notifications-page',
  adminChapters: '/admin/chapters',
  adminExamResults: '/admin/exams/results',
  adminCompletedExams: '/admin/completed-exams',
  adminBulkStudents: '/admin/students/bulk-register',
  adminStudents: '/admin/students',
  adminSchools: '/admin/schools',
  adminProfile: '/admin/profile',

  // ── Super Admin role-prefixed routes ──
  superAdminDashboard: '/super-admin/dashboard',
  superAdminBulkStudents: '/super-admin/students/bulk-register',
  superAdminStudents: '/super-admin/students',
  superAdminSchools: '/super-admin/schools',
  superAdminQuestionBank: '/super-admin/question-bank',
  superAdminChapters: '/super-admin/chapters',
  superAdminCreateQuestion: '/super-admin/question-bank/create',
  superAdminImportQuestions: '/super-admin/question-bank/import',
  superAdminEditQuestion: '/super-admin/question-bank/:id/edit',
  superAdminLanguages: '/super-admin/languages',
  superAdminTranslations: '/super-admin/translations',
  superAdminImportTranslations: '/super-admin/languages/import',
  superAdminExamBlueprints: '/super-admin/exam-blueprints',
  superAdminAutoGenerateExam: '/super-admin/exams/generate',
  superAdminMockTests: '/super-admin/mock-tests',
  superAdminExams: '/super-admin/mock-tests',
  superAdminExamResults: '/super-admin/exams/results',
  superAdminCompletedExams: '/super-admin/completed-exams',
  superAdminExamManager: '/super-admin/exam-manager',
  superAdminUploadPaper: '/super-admin/exam-manager/upload',
  superAdminExamImportHistory: '/super-admin/exam-manager/history',
  superAdminExamScheduling: '/super-admin/exam-scheduling',
  superAdminStrategyRules: '/super-admin/strategy-rules',
  superAdminLeaderboard: '/super-admin/leaderboard',
  superAdminHistoricalDatasets: '/super-admin/historical-datasets',
  superAdminControlCenter: '/super-admin/control-center',
  superAdminApprovalQueue: '/super-admin/approval-queue',
  superAdminAuditLogs: '/super-admin/audit-logs',
  superAdminNotifications: '/super-admin/notifications',
  superAdminInstitutionDashboard: '/super-admin/institution',
  superAdminInstitutionBatches: '/super-admin/institution/batches',
  superAdminInstitutionBulkUpload: '/super-admin/institution/bulk-upload',
  superAdminInstitutionReports: '/super-admin/institution/reports',
  superAdminProfile: '/super-admin/profile',

  // ── Parent role-prefixed routes ──
  parentDashboardHome: '/parent/dashboard',
  parentWardProgress: '/parent/ward-progress',
  parentProfile: '/parent/profile',
});

// ** Misc **
export const NOT_FOUND_PATH = '*';
