/**
 * Route path registry (repo convention: PUBLIC_NAVIGATION / PRIVATE_NAVIGATION
 * objects, never inline path strings).
 */

// ** Unauthenticated paths **
export const PUBLIC_NAVIGATION = Object.freeze({
  home: '/',
  login: '/login',
  register: '/register',
});

// ** Authenticated paths **
export const PRIVATE_NAVIGATION = Object.freeze({
  // ── Legacy flat paths (kept for backward compatibility / redirects) ──
  dashboard: '/dashboard',
  availableExams: '/exams',
  examInterface: '/exam/:examId/attempt/:attemptId',
  examResult: '/exam/result/:attemptId',
  myHistory: '/history',
  languages: '/languages',
  examScheduling: '/exam-scheduling',
  strategyRules: '/strategy-rules',
  leaderboard: '/leaderboard',
  historicalDatasets: '/historical-datasets',
  performanceTrends: '/performance-trends',
  parentDashboard: '/parent-dashboard',
  institutionDashboard: '/institution/dashboard',
  institutionStudents: '/institution/students',
  institutionRankList: '/institution/rank-list',
  institutionBatches: '/institution/batches',
  institutionBulkUpload: '/institution/bulk-upload',
  institutionReports: '/institution/reports',
  institutionProfile: '/institution/profile',
  adminControlCenter: '/admin',
  adminApprovalQueue: '/admin/approvals',
  adminAuditLogs: '/admin/audit-logs',
  adminNotifications: '/admin/notifications',
  notifications: '/notifications',
  examDetails: '/exams/:examId',
  academicCalendar: '/exam-calendar',
  profile: '/profile',

  // ── Student role-prefixed routes ──
  studentDashboard: '/student/dashboard',
  studentExams: '/student/exams',
  studentExamDetails: '/student/exams/:examId',
  studentNotifications: '/student/notifications',
  studentHistory: '/student/history',
  studentCalendar: '/student/exam-calendar',
  studentTrends: '/student/performance-trends',
  studentComparison: '/student/comparison',
  studentLeaderboard: '/student/leaderboard',
  studentProfile: '/student/profile',

  // ── Admin role-prefixed routes ──
  adminDashboard: '/admin/dashboard',
  adminLanguages: '/admin/languages',
  adminExamManager: '/admin/exam-manager',
  adminUploadPaper: '/admin/exam-manager/upload',
  adminManualQuestions: '/admin/exams/:examId/question-paper/add',
  adminExamImportHistory: '/admin/exam-manager/history',
  adminExamScheduling: '/admin/exam-scheduling',
  adminScheduleExam: '/admin/exams/schedule',
  adminStrategyRules: '/admin/strategy-rules',
  adminLeaderboard: '/admin/leaderboard',
  adminHistoricalDatasets: '/admin/historical-datasets',
  adminControlCenterPage: '/admin/control-center',
  adminApprovalQueuePage: '/admin/approval-queue',
  adminAuditLogsPage: '/admin/audit-logs-page',
  adminNotificationsPage: '/admin/notifications-page',
  adminChapters: '/admin/chapters',
  adminExamResults: '/admin/exams/results',
  adminCompletedExams: '/admin/completed-exams',
  adminBulkStudents: '/admin/students/bulk-register',
  adminPublicRegistrations: '/admin/public-registrations',
  adminStudents: '/admin/students',
  adminSchools: '/admin/schools',
  adminProfile: '/admin/profile',

  // ── Super Admin role-prefixed routes ──
  superAdminDashboard: '/super-admin/dashboard',
  superAdminRegistrations: '/super-admin/registrations',
  superAdminPublicRegistrations: '/super-admin/public-registrations',
  superAdminBulkStudents: '/super-admin/students/bulk-register',
  superAdminStudents: '/super-admin/students',
  superAdminSchools: '/super-admin/schools',
  superAdminChapters: '/super-admin/chapters',
  superAdminLanguages: '/super-admin/languages',
  superAdminAiQuestionPaperTranslation: '/super-admin/ai-question-paper-translation',
  superAdminExamResults: '/super-admin/exams/results',
  superAdminExamResultProcessing: '/super-admin/exams/result-processing',
  superAdminCompletedExams: '/super-admin/completed-exams',
  superAdminExamManager: '/super-admin/exam-manager',
  superAdminUploadPaper: '/super-admin/exam-manager/upload',
  superAdminManualQuestions: '/super-admin/exams/:examId/question-paper/add',
  superAdminExamImportHistory: '/super-admin/exam-manager/history',
  superAdminExamScheduling: '/super-admin/exam-scheduling',
  superAdminScheduleExam: '/super-admin/exams/schedule',
  superAdminStrategyRules: '/super-admin/strategy-rules',
  superAdminLeaderboard: '/super-admin/leaderboard',
  superAdminHistoricalDatasets: '/super-admin/historical-datasets',
  superAdminControlCenter: '/super-admin/control-center',
  superAdminApprovalQueue: '/super-admin/approval-queue',
  superAdminAuditLogs: '/super-admin/audit-logs',
  superAdminNotifications: '/super-admin/notifications',
  superAdminInstitutionDashboard: '/super-admin/institution',
  superAdminInstitutionBatches: '/super-admin/institution/batches',
  superAdminInstitutionBulkUpload: '/super-admin/institution/bulk-upload',
  superAdminInstitutionReports: '/super-admin/institution/reports',
  superAdminStaff: '/super-admin/staff',
  superAdminBilling: '/super-admin/billing',
  superAdminAcademicCalendar: '/super-admin/academic-calendar',
  superAdminProfile: '/super-admin/profile',

  // ── Staff role-prefixed routes ──
  staffDashboard: '/staff/dashboard',
  staffBilling: '/staff/billing',
  staffSchools: '/staff/schools',
  staffBulkStudents: '/staff/students/bulk-register',
  staffStudents: '/staff/students',
  staffScheduledExams: '/staff/exams/pending-paper',
  staffReports: '/staff/reports',
  staffApprovalQueue: '/staff/approvals',
  staffNotifications: '/staff/notifications',
  staffProfile: '/staff/profile',

  // ── General Manager role-prefixed routes ──
  generalManagerDashboard: '/general-manager/dashboard',
  generalManagerStudents: '/general-manager/students',
  generalManagerBulkStudents: '/general-manager/students/bulk-register',
  generalManagerSchools: '/general-manager/schools',
  generalManagerChapters: '/general-manager/chapters',
  generalManagerLanguages: '/general-manager/languages',
  generalManagerExamScheduling: '/general-manager/exam-scheduling',
  generalManagerUploadPaper: '/general-manager/exam-manager/upload',
  generalManagerCompletedExams: '/general-manager/completed-exams',
  generalManagerReports: '/general-manager/reports',
  generalManagerApprovalQueue: '/general-manager/approvals',
  generalManagerBilling: '/general-manager/billing',
  generalManagerStrategyRules: '/general-manager/strategy-rules',
  generalManagerLeaderboard: '/general-manager/leaderboard',
  generalManagerHistoricalDatasets: '/general-manager/historical-datasets',
  generalManagerAuditLogs: '/general-manager/audit-logs',
  generalManagerNotifications: '/general-manager/notifications',
  generalManagerProfile: '/general-manager/profile',

  // ── Manager role-prefixed routes ──
  managerDashboard: '/manager/dashboard',
  managerStudents: '/manager/students',
  managerSchools: '/manager/schools',
  managerReports: '/manager/reports',
  managerApprovalQueue: '/manager/approvals',
  managerBilling: '/manager/billing',
  managerNotifications: '/manager/notifications',
  managerProfile: '/manager/profile',

  // ── Operator role-prefixed routes ──
  operatorDashboard: '/operator/dashboard',
  operatorStudents: '/operator/students',
  operatorBulkStudents: '/operator/students/bulk-register',
  operatorSchools: '/operator/schools',
  operatorChapters: '/operator/chapters',
  operatorLanguages: '/operator/languages',
  operatorExamScheduling: '/operator/exam-scheduling',
  operatorScheduledExams: '/operator/exams/pending-paper',
  operatorUploadPaper: '/operator/exam-manager/upload',
  operatorExamUploadPaper: '/operator/exams/:examId/question-paper/upload',
  operatorViewQuestionPaper: '/operator/exams/:examId/question-paper/view',
  operatorExamImportHistory: '/operator/exam-manager/history',
  operatorCompletedExams: '/operator/completed-exams',
  operatorReports: '/operator/reports',
  operatorApprovalQueue: '/operator/approvals',
  operatorBilling: '/operator/billing',
  operatorLeaderboard: '/operator/leaderboard',
  operatorNotifications: '/operator/notifications',
  operatorProfile: '/operator/profile',

  // ── Accountant role-prefixed routes ──
  accountantDashboard: '/accountant/dashboard',
  accountantBilling: '/accountant/billing',
  accountantReports: '/accountant/reports',
  accountantNotifications: '/accountant/notifications',
  accountantProfile: '/accountant/profile',

  // ── Sales Agent role-prefixed routes ──
  salesAgentDashboard: '/sales-agent/dashboard',
  salesAgentSchools: '/sales-agent/schools',
  salesAgentReports: '/sales-agent/reports',
  salesAgentNotifications: '/sales-agent/notifications',
  salesAgentProfile: '/sales-agent/profile',

  // ── Parent role-prefixed routes ──
  parentDashboardHome: '/parent/dashboard',
  parentWardProgress: '/parent/ward-progress',
  parentProfile: '/parent/profile',
});

// ** Misc **
export const NOT_FOUND_PATH = '*';
